var gdoApp = angular.module('mainApp', [
	'ngResource',
	'ngRoute',
	'ui.router',
	'ui.bootstrap',
  'ui-notification',
	'ngAnimate',
	'angularUtils.directives.dirPagination',
	'ngStorage',
	'taira-multiselect',
	'ngFileUpload',
	'ngTagsInput',
	'angularUtils.ajaxLoader',
	'angularMoment',
	'ui.calendar',
  'ngMessages',
  'ngSanitize',
  'ui.select',
  'ngMask',
  'angular-confirm',
  'summernote',
  'Gdo',
  'xeditable',
  'destinos-autocomplete',
  'ui.select',
  'ngMap',
  'ui.bootstrap.datetimepicker',
  'toggle-switch',
  'chart.js',
  'wu.masonry'
]);

console.log("");
console.log("oooooooo++++++++++++++++++++++++++++++++++++++++++/////////////////////////+++++++++++++++++++++++++");
console.log("ooooooooo+++++++++++++++++++++++++++++++++++//////////////////////////////////////++/+++++++++++++++");
console.log("ooooooo++++++++++++++++++++++++++++++++//////////////////////////////////////////////+++++++++++++++");
console.log("oooooo++++++++++++++++++++++++++++++//////////////////////////////////////////////////++++++++++++++");
console.log("oooooo+++++++++++++++++++++++++++++/////////////////////////////////////////////////////++++++++++++");
console.log("oooo++++++++++++++++++++++++++++++//////////////////////////////////////////////////////++++++++++++");
console.log("ooo+++++++++++++++++++++++++++++++//////////////////////////////////////////////////////++++++++++++");
console.log("oo+++++++++++++++++++++++++++++/+//////////////////////////////////////////////////////////+++++++++");
console.log("o+++++++++++++++++++++++++++++++////////////+ossssyssso+/////////////////////////////////////+++++++");
console.log("o++++++++++++++++++++++++++++++++///////+ssydmmNNNNNNNNdyso+/////////////////////////////////+++++++");
console.log("o+++++++++++++++++++++++++++++++++++++oydNNNNNNNNNNNNNNNNNmdo///////////////////////////////++++++++");
console.log("o++++++++++++++++++++++++++++++++++++ymNNNNNNNNNNNNNNNNNNNNNmho+//////////////////////////++++++++++");
console.log("o++++++++++++++++++++++++++++++/+//+smNNNNNNNNNNNNNNNNNNNNNNNNmy/////////////////////////+++++++++++");
console.log("o++++++++++++++++++++++++++++//////omNNNmmmmmmmdmmmmmmmmNNNNNNmms//////////////////////+++++++++++++");
console.log("++++++++++++++++++++++++++++++//+++ymmmmdhhhhhyyyyyhyhhhhdmmmNNmd+//////////////+/////++++++++++++++");
console.log("++++++++++++++++++++++++++++/+++++odNNmdhyyyyssssssssssyyyyhdmmNms/////////////////+++++++++++++++++");
console.log("o++++++++++++++++++++++++++++++++oymNNmhhyyyyssssssssssyyyyyhdmNNy///////////////////+++++++++++++++");
console.log("o++++++++++++++++++++++++++++++++odNNNmhhyyssssssssssssssyyyhmmNNh+/////////////////++++++++++++++++");
console.log("o+++++++++++++++++++++++++++++++++dNNNdhhyyyyyyyssossyyyyyyyhdmmNh+//////////////////+++++++++++++++");
console.log("++++++++++++++++++++++++++++++++++hmNmdhddddddddhssyhdddddddddmNNmo/////////////////++++++++++++++++");
console.log("++++++++++++++++++++++++++++++++++odNmdhdddddhyhhysyhhhdddddhhmNmh+/////////////////++++++++++++++++");
console.log("++++++++++++++++++++++++++++++++++ohmmdhhhhhyyyhhhyyhhyyyhhhhhdmh++//////////////////+++++++++++++++");
console.log("+++++++++++++++++++++++++++++++++++hdmdhyyyyyyyyhhyyhhyyyyyyyhhhy+////////////++////++++++++++++++++");
console.log("+++++++++++++++++++++++++++++++++++ohhhhyyyyyssyhhyyhhsssyyyyhhy+//////+++//++++//++++++++++++++++++");
console.log("++++++++++++++++++++++++++++++++++++shhhhyyysssyhhhhhhysssyyhhho+/+///+++//+/+++++++++++++++++++++++");
console.log("+++++++++++++++++++++++++++++++++++++hdhhyyyyyhhhhyyhhhhyyyhhhh++++++++/++++++++++++++++++++++++++++");
console.log("++++++++++++++++++++++++++++++++++++++hdhhyyyyhdddhhdddhhyyhhhy+++++//////++++++++++++++++++++++++++");
console.log("++++++++++++++++++++++++++++++++++++++ohdhhyyyyyyyyyyyhyyyhhhy++++/+++++/+++++++++++++++++++++++++++");
console.log("++++++++++++++++++++++++++++++++++++++yhddhhhhyyysyyyyyhhhhhdy+//////++/++++++++++++++++++++++++++++");
console.log("+++++++++++++++++++++++++++++++++++++dmhhddddhhhyyyyyyhdddddhddo//++/+++++++++++++++++++++++++++++++");
console.log("o++++++++++++++++++++++++++++++++++sdNdhhhdddddhhhyyyhddmmdhhymmy+/+////++++++++++++++++++++++++++++");
console.log("o+++++++++++++++++++++++++++++++++ymNmyyhhhdddmmddddddmmmdhyysmNNdso+////+++++++++++++++++++++++++++");
console.log("oo+++++++++++++++++++++++++oosyhdmNNNmyosyyhhdddddddddmdhyysoymNNNNmdhyo++++++++++++++++++++++++++++");
console.log("ooo++++++++++++++++oosyyhddmmmNNNNNNNmyo+oyyyyhhhdddhhyyys++odNNNNNNNNNmmdhyso++++++++++++++++++++++");
console.log("ooo++++++++++++oyhdmmmNNNNNNNNNNNNNNNNhoo++syyyyyyyyysss++++smNNNNNNNNNNNNNNmmddhso+++++++++++++++++");
console.log("ooooo++++++oshdmNNNNNNNNNNNNNNNNNNNNNmdoo+++oyssssssso+//++odNNNNNNNNNNNNNNNNNNNNNmmdys+++++++++++++");
console.log("oooooooooydmNNNNNNNNNNNNNNNNNNNNNNNNNNmso++smmhyyyyydy+//++hNNNNNNNNNNNNNNNNNNNNNNNNNNmmhso+++++++++");
console.log("ooooooooymNNNNNNNNNNNNNNNNNNNNNNNNNNNNNho++yhhdmmNNNms++/+smNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmhyo++++++");
console.log("oooooooomNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNms+++++oNNNNd+++o+odNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNdo+++++");
console.log("oooooooymNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNy+++++sNNNd+/+oo+yNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNy+++++");
console.log("ooooooodNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNd+++++hNNNy/+o++smNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNh+++++");
console.log("oooooosmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNms++ohNNNNd+++++dNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNm+++++");
console.log("ooooooyNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNy++hNNNNNNy+++yNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNms++++");
console.log("oooooodNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNdooNNNNNNNd++omNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNy++++");
console.log("ooooosmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmshNNNNNNNNo+hNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNh++++");
console.log("oooooyNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNymNNNNNNNNssmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNh++++");
console.log("ssoosdNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNNNNNNNNNsdNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNh++++");
console.log("ssoosmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNdNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmo+++");
console.log("ssssyNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNs+o+");
console.log("sssshNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNdooo");
console.log("ssssdNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmooo");




